name: Deploy client

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
env:
  IMAGE_REGISTRY: "ghcr.io/emilhallberg"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy client
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ github.token }}"

      - name: Set environment variables
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "IMAGE_REGISTRY=${{ env.REGISTRY }}/portfolio/client" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: client
          push: true
          tags: "${{ env.IMAGE_REGISTRY }}:latest,${{ env.IMAGE_REGISTRY }}:${{ env.SHA_SHORT }}"
          cache-from: "type=registry,ref=${{ env.IMAGE_REGISTRY }}:buildcache"
          cache-to: "type=registry,ref=${{ env.IMAGE_REGISTRY }}:buildcache,mode=max"

      - name: Commit files
        run: |
          git clone "https://${{ secrets.INFRASTRUCTURE_USERNAME }}:${{ secrets.INFRASTRUCTURE_PASSWORD }}@${{ secrets.INFRASTRUCTURE_REPOSITORY }}" repo
          cd repo/charts/emil-portfolio/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          yq eval ".client.image = \"${{ env.IMAGE_REGISTRY }}:${{ env.SHA_SHORT }}\"" --inplace values.yaml
          git commit -am "Update emil portfolio client image"
          git push